In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/Student_Performance_New.csv")

In [ ]:
df.head()

   Hours Studied  ...  Performance Index
0              7  ...                 91
1              4  ...                 65
2              8  ...                 45
3              5  ...                 36
4              7  ...                 66

[5 rows x 5 columns]

In [ ]:
df.shape

(10000, 5)

In [ ]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Sleep Hours',
       'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Sleep Hours                       10000 non-null  int64
 3   Sample Question Papers Practiced  10000 non-null  int64
 4   Performance Index                 10000 non-null  int64
dtypes: int64(5)
memory usage: 390.8 KB

In [ ]:
df.head()

   Hours Studied  ...  Performance Index
0              7  ...                 91
1              4  ...                 65
2              8  ...                 45
3              5  ...                 36
4              7  ...                 66

[5 rows x 5 columns]

In [ ]:
df.describe()

       Hours Studied  ...  Performance Index
count   10000.000000  ...       10000.000000
mean        4.992900  ...          55.224800
std         2.589309  ...          19.212558
min         1.000000  ...          10.000000
25%         3.000000  ...          40.000000
50%         5.000000  ...          55.000000
75%         7.000000  ...          71.000000
max         9.000000  ...         100.000000

[8 rows x 5 columns]

In [ ]:
print(df.isnull().sum())

Hours Studied                       0
Previous Scores                     0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [ ]:
print(df.duplicated().sum())

234

In [ ]:
X = df[["Hours Studied", "Previous Scores", "Sleep Hours", "Sample Question Papers Practiced"]]
y = df["Performance Index"]

In [ ]:
print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   Hours Studied  ...  Sample Question Papers Practiced
0              7  ...                                 1
1              4  ...                                 2
2              8  ...                                 2
3              5  ...                                 2
4              7  ...                                 5

[5 rows x 4 columns]

Target:
0    91
1    65
2    45
3    36
4    66
Name: Performance Index, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (8000, 4)
X_test shape: (2000, 4)
y_train shape: (8000,)
y_test shape: (2000,)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
print("Coefficients:")
print(model.coef_)

Coefficients:
[2.85289351 1.01703572 0.47331832 0.19172629]

In [ ]:
print("Intercept:")
print(model.intercept_)

Intercept:
-33.60206732749288

In [ ]:
coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print(coefficients)

                            Feature  Coefficient
0                     Hours Studied     2.852894
1                   Previous Scores     1.017036
2                       Sleep Hours     0.473318
3  Sample Question Papers Practiced     0.191726

In [ ]:
largest = coefficients.iloc[coefficients["Coefficient"].abs().argmax()]

print("Feature with greatest impact:")
print(largest)

Feature with greatest impact:
Feature        Hours Studied
Coefficient         2.852894
Name: 0, dtype: object

In [ ]:
y_pred = model.predict(X_test)
print(y_pred[:10])

[55.00786377 22.31444624 47.59404705 30.97597184 43.31471122 59.38258169
 45.60540054 86.75267138 37.99886877 71.74077885]

In [ ]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison.head(10)

   Actual  Predicted
0      51  55.007864
1      20  22.314446
2      46  47.594047
3      28  30.975972
4      41  43.314711
5      59  59.382582
6      48  45.605401
7      87  86.752671
8      37  37.998869
9      73  71.740779

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

Mean Absolute Error: 1.6296726874197016
Mean Squared Error: 4.182254914593815
R² Score: 0.9887144552384186

In [ ]:
prediction = model.predict([[7,80,7,5]])

print("Predicted Performance Index:", prediction[0])

Predicted Performance Index: 72.00290421447264

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(